sudo: required
language: node_js
node_js:
  - "node"
cache: yarn
install: yarn
services:
  - docker
before_install:
  - docker build -t sredahan/ci-unit-tests -f Dockerfile.dev .
script:
  - docker run sredahan/ci-unit-test yarn run test -- --coverage

